#
# This spec file was automatically generated by cpan2rpm v2.009
# For further information please refer to: http://perl.arix.com/
#
%define pkgname    cpan2rpm
%define filelist %{pkgname}-%{version}-filelist
%define NVR %{pkgname}-%{version}-%{release}
Summary:       cpan2rpm - A Perl module packager
Name:          cpan2rpm
Version:       2.009
Release:       1
Group:         Applications/CPAN
Vendor:        Erick Calder <ecalder@cpan.org>
Packager:      Arix International <cpan2rpm@arix.com>
License:       Artistic
Url:           http://www.cpan.org
BuildRoot:     %{_tmppath}/%{name}-%{version}-%(id -u -n)
BuildArch:     noarch
Source:        %{pkgname}-%{version}.tar.gz
Requires: rpm-build
%description
cpan2rpm [options] <module>
This script generates an RPM package from a Perl module.  It uses the standard RPM file structure and creates a spec file, a source RPM, and a binary, leaving these in their respective directories.
The script can operate on local files, urls and CPAN module names.  Install this package if you want to create RPMs out of Perl modules.
#
# This package was automatically generated with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#
%prep
%setup -q -n cpan2rpm-2.009 
chmod -R u+w %{_builddir}/cpan2rpm-2.009
%build
CFLAGS="$RPM_OPT_FLAGS"
%{__perl} Makefile.PL `%{__perl} -MExtUtils::MakeMaker -e 'if ($ExtUtils::MakeMaker::VERSION =~ /5\.9[1-6]|6\.0[0-5]/) {print "PREFIX=%{buildroot}%{_prefix}";}'`
%{__make} 
%{__make} test
%install
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}
%{makeinstall} `%{__perl} -MExtUtils::MakeMaker -e 'if ($ExtUtils::MakeMaker::VERSION <= 6.05) {print "PREFIX=%{buildroot}%{_prefix}";} else {print "DESTDIR=%{buildroot}";}'`
[ -x /usr/lib/rpm/brp-compress ] && /usr/lib/rpm/brp-compress
# remove special files
find %{buildroot} -name "perllocal.pod" \
-o -name ".packlist"                \
-o -name "*.bs"                     \
|xargs -i rm -f {}
# no empty directories
find %{buildroot}%{_prefix}             \
-type d -depth                      \
-exec rmdir {} \; 2>/dev/null
%{__perl} -MFile::Find -le '
find({ wanted => \&wanted, no_chdir => 1}, "%{buildroot}");
print "%defattr(-,root,root)";
print "%doc perl.req.patch README Changes";
for my $x (sort @dirs, @files) {
push @ret, $x unless indirs($x);
}
print join "\n", sort @ret;
sub wanted {
return if /auto$/;
my $f = $_; s|^%{buildroot}||;
return unless length;
return $files[@files] = $_ if -f $f;
$d = $_;
/$d/ && return for reverse sort @INC;
$d =~ /$_/ && return
for qw|/etc %_prefix/man %_prefix/bin %_prefix/share|;
$dirs[@dirs] = $_;
}
sub indirs {
my $x = shift;
$x =~ /^$_/ && $x ne $_ && return 1 for @dirs;
}
' > %filelist
[ -z %filelist ] && {
echo "ERROR: empty %files listing"
exit -1
}
%clean
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}
%files -f %filelist
%changelog
* Thu Jan 2 2003 ekkis@beowulf
- Initial build.
