--- #YAML:1.0
name:               cpan2rpm
version:            2.028_02
abstract:           A Perl module packager
author:
    - Erick Calder <ecalder@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::MakeMaker:  5.4302
    HTTP::Request:        0
    LWP::UserAgent:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
